export enum UserFieldLock {
  NAME = 'NAME',
  ADDRESS = 'ADDRESS',
  PHONE_NO = 'PHONE_NO',
  E_MAIL = 'E_MAIL',
  BANK_INFORMATION = 'BANK_INFORMATION',
  PASSWORD = 'PASSWORD',
  SECURITY_QUESTION = 'SECURITY_QUESTION',
  INVOICE_DIGITAL_ONLY = 'INVOICE_DIGITAL_ONLY',
  LOCK_ACCOUNT = 'LOCK_ACCOUNT'
}
